using Microsoft.Xna.Framework;

namespace Deathborn.Client.Rendering.Characters;

/// <summary>Swordsman V2 sprite sheets — 8 directions, tight per-frame atlas.</summary>
internal static class SwordsmanV2AnimationSpecs
{
    public const int Directions = 8;
    public const float IdleFrameDuration = 0.18f;
    public const float WalkFrameDuration = 0.12f;
    public const float AttackFrameDuration = 0.075f;

    // Generated by scripts/regenerate_swordsman_v2_atlas.py — matches walk on-screen body height.
    private static readonly float[] IdleRowDrawScale =
    [
        0.786f, // row 0
        1.207f, // row 1
        0.811f, // row 2
        1.200f, // row 3
        0.805f, // row 4
        1.193f, // row 5
        0.912f, // row 6
        1.286f, // row 7
    ];

    // Generated by scripts/regenerate_swordsman_v2_atlas.py — normalizes every row to tallest body height.
    private static readonly float[] WalkRowDrawScale =
    [
        1.048f, // row 0
        1.021f, // row 1
        1.100f, // row 2
        1.000f, // row 3
        1.065f, // row 4
        1.021f, // row 5
        1.138f, // row 6
        1.053f, // row 7
    ];

    // Sheet rows: 0=S, 1=SE, 2=E, 3=NE, 4=N, 5=NW, 6=W, 7=SW (see prompts/sprites/Player/manifest.json).
    private static readonly int[] IdleRowMap =
    [
        0, // Down — South
        7, // DownLeft — South-West
        6, // Left — West
        5, // UpLeft — North-West
        4, // Up — North
        3, // UpRight — North-East
        2, // Right — East
        1, // DownRight — South-East
    ];

    private static readonly int[] WalkRowMap =
    [
        0, // Down — South
        7, // DownLeft — South-West
        6, // Left — West
        5, // UpLeft — North-West
        4, // Up — North
        3, // UpRight — North-East
        2, // Right — East
        1, // DownRight — South-East
    ];

    public static AnimationSpecification For(CharacterClip clip) => clip switch
    {
        CharacterClip.Idle or CharacterClip.Cast => Idle,
        CharacterClip.Run or CharacterClip.Roll => Walk,
        CharacterClip.Attack => Attack,
        CharacterClip.Hurt => SwordsmanAnimationSpecs.Hurt,
        CharacterClip.Death => SwordsmanAnimationSpecs.Death,
        _ => Idle,
    };

    public static AnimationSpecification Idle => new()
    {
        FramesPerDirection = 6,
        Directions = Directions,
        FrameDuration = IdleFrameDuration,
        Layout = AnimationSheetLayout.TightFrames,
        DirectionRowMap = IdleRowMap,
        DirectionRowDrawScale = IdleRowDrawScale,
    };

    public static AnimationSpecification Walk => new()
    {
        FramesPerDirection = 8,
        Directions = Directions,
        FrameDuration = WalkFrameDuration,
        Layout = AnimationSheetLayout.TightFrames,
        DirectionRowMap = WalkRowMap,
        DirectionRowDrawScale = WalkRowDrawScale,
    };

    public static AnimationSpecification Attack => new()
    {
        FramesPerDirection = 8,
        Directions = Directions,
        FrameDuration = AttackFrameDuration,
        Layout = AnimationSheetLayout.TightFrames,
    };
}
